version: "3.9"

services:
  backend:
    image: ${BACKEND_IMAGE:-4gray/iptvnator-backend:latest}
    network_mode: host
    restart: unless-stopped
    environment:
      - CLIENT_URL=http://127.0.0.1:${FRONTEND_PORT:-4333}
      - PORT=${BACKEND_PORT:-7333}

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/cgg888/iptvnator:latest}
    network_mode: host
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://127.0.0.1:${BACKEND_PORT:-7333}
      - FRONTEND_PORT=${FRONTEND_PORT:-4333}
